site_name: Sitar Simulation Framework
site_description: A cycle-based discrete-event modeling framework
site_author: Neha Karanjkar
site_dir: generated_site

repo_url: https://github.com/sitar-sim/sitar
repo_name: sitar-sim/sitar
theme:
  #logo: assets/sitar_logo.png
  name: material
  highlightjs: false
  
  palette: 
    # Palette toggle for light mode
    - scheme: colorful
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    #- navigation.expand
    - navigation.tracking
    - navigation.instant
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: .
  - pymdownx.superfences
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
extra_css:
  - stylesheets/extra.css

nav:
  - Introduction:
      - What is Sitar: index.md
      - Getting Started: getting_started.md

  - Basic Concepts:
      - Components: components_modules_nets.md
      - Timing and Execution: timing_and_execution_model.md
      - Module Behavior: module_behavior.md
      - Tokens, Input and Output: io_and_tokens.md

  - Language and Examples:
      - Describing Structure:
          - Modules: language_and_examples/modules.md
          - Nets and Ports: language_and_examples/nets_and_ports.md
          - Hierarchy: language_and_examples/hierarchy.md
          - Parameters: language_and_examples/parameters.md
          - Regular Structures: language_and_examples/regular_structures_for_loops.md

      - Describing Behavior:
          - Sequence: language_and_examples/sequence.md
          - Atomic and Compound Statements: language_and_examples/atomic_and_compound_statements.md
          - Code Blocks: language_and_examples/code_blocks.md
          - Wait: language_and_examples/wait.md
          - Log: language_and_examples/logging.md
          - If-Else: language_and_examples/if_else.md
          - Do-While: language_and_examples/do_while.md
          - Parallel: language_and_examples/parallel.md
          - Procedures: language_and_examples/procedures.md

      - Useful Constructs:
          - Templates: language_and_examples/templates.md
          - Advanced Logging: language_and_examples/advanced_logging.md

  - Examples:
      - Basic Examples:
          - Shift Register: language_and_examples/basic_examples/shift_register.md
          - State Machine: language_and_examples/basic_examples/state_machine.md
          - Producer Consumer: language_and_examples/basic_examples/producer_consumer.md

      - Advanced Examples:
          - Processor and Memory: language_and_examples/advanced_examples/processor_model.md
          - Mesh: language_and_examples/advanced_examples/mesh.md

  - Parallel Execution:
      - Enabling Parallel Execution: parallel_execution.md
      - Measuring Speedup: speedups.md

  - How Sitar Works:
      - Translation: how_sitar_works/translation.md
      - Execution Semantics: how_sitar_works/execution_semantics.md

  - More About Sitar:
      - References: references.md
      - Authors: authors.md
      - Development Notes: development.md

